A3 check brackets
nikolay24534/PY111 pull request #2
Opened 2020-12-20 15:03 UTC by nikolay24534

Безверхний Николай Олегович

2020-12-22 17:27 UTC, aeksei requested changes
---

Если стоит статус **Changes requested**, то нужно в данную ветку внести обязательные изменения, которые представлены ниже. Если выше представлены комментарии, то они носят рекомендательный характер.
После нужно сделать "push", тогда коммиты с изменениями сразу попадут в "pull request". 
После этого нужно будет запросить "re-request review"

2020-12-22 17:27 UTC, aeksei commented on Tasks/a2_priority_queue.py
> +    return my_prior_queue[priority][ind] if my_prior_queue[priority][ind] else None
А точно нужно проверять наличие элемента по индексу?  
`if my_prior_queue[priority][ind]` тут наверное вы хотели проверить не пустая ли очередь с указанным приоритетом

2020-12-22 17:27 UTC, aeksei commented on Tasks/a3_check_brackets.py
> +    close_bracket = ')'
Их я бы сделал константами, чтобы нагляднее было

2020-12-22 17:28 UTC, aeksei commented
В дальнейшем, пожалуйста, разделяйте задачи по отдельным pull request

2020-12-23 07:58 UTC, nikolay24534 commented on Tasks/a2_priority_queue.py
> +    return my_prior_queue[priority][ind] if my_prior_queue[priority][ind] else None
Думаю, что точно нужно. Потому что если очередь не пуста, а нужно элемента там нет, то будет IndexError.
Попробую без индекса.

2020-12-24 16:53 UTC, aeksei approved these changes
Проверено

---

Если стоит **Changes approved**, то смело можно сливать ветки. 
И после слияния удалять ветку.

Всё что указано просто комментариями, носит рекомендательный характер.
Для моментов, которые нужно исправить, я буду запрашивать изменения.

2020-12-26 15:51 UTC, merged